-- ──────────────────────────────────────────────────────────────────
-- Migration 028: Accounting / Finance module
--
-- Why
-- ───
-- MTCPL has been running its finance side on paper + memory. Bills
-- from cement / steel / scaffolding / motor / CNC-tool suppliers
-- arrive, get reviewed manually by the owner, get paid manually,
-- and the outstanding balance lives in nobody's head except the
-- owner's. The ask is to move that workflow into the software the
-- same way cutting and carving already are.
--
-- Two new roles enter the system:
--   • biller     — fills the bill-entry form (description, amount,
--                  GST%, beneficiary). Submissions land in
--                  pending_approval until the owner reviews them
--                  against the physical paper bill.
--   • accountant — once a bill is approved, sees it in a due-bills
--                  dashboard (vendor + age filters + KPI cards).
--                  Multi-select to propose a pay-today batch.
--                  Marks each payment paid with method + reference.
--                  Partial payments are first-class.
--
-- Approach
-- ────────
-- Three new tables, orthogonal to anything we already have:
--   • bill_vendors  — the beneficiary master. Distinct from the
--                     existing public.vendors table, which is reserved
--                     for carving CNC / Manual vendors. The two roles
--                     never overlap in practice (cement suppliers
--                     don't carve marble).
--   • bills         — the master bill record. amount_outstanding is a
--                     STORED GENERATED column so queue queries can
--                     index it directly. Token generated by trigger
--                     in format TOK-YYYY-NNNNN — cross-references a
--                     future inventory row (v2; column exists as a
--                     stub).
--   • bill_payments — one row per pay-today proposal. Lifecycle
--                     proposed → confirmed → paid (or cancelled).
--                     A single bill can have many rows over time
--                     (partial payments). A trigger keeps
--                     bills.amount_paid in sync whenever a payment
--                     row enters or leaves the 'paid' state.
--
-- Existing data is untouched. No backfill. The two ALTER TYPE
-- statements that extend public.app_role have to run OUTSIDE the
-- BEGIN/COMMIT — Postgres refuses ALTER TYPE ADD VALUE inside a
-- transaction.
--
-- Out of scope (v1)
-- ─────────────────
--   • Inventory tracking (bills.inventory_ref_token stays NULL).
--   • Bill scan / photo upload (no Supabase Storage infra yet).
--   • TDS withholding.
--   • Multi-currency (₹ only).
--
-- ──────────────────────────────────────────────────────────────────

ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'biller';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'accountant';

BEGIN;

-- ── Enums ─────────────────────────────────────────────────────────
-- Two separate enums for bill vs payment lifecycle. A bill has many
-- payments and their states evolve independently — sharing a single
-- enum would be lossy. Same split as cut_block_status vs
-- cut_session_status.
DO $$ BEGIN
  CREATE TYPE public.bill_status AS ENUM (
    'pending_approval',
    'approved',
    'rejected',
    'fully_paid',
    'cancelled'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.bill_payment_status AS ENUM (
    'proposed',
    'confirmed',
    'paid',
    'cancelled'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.payment_method AS ENUM (
    'cash',
    'cheque',
    'neft',
    'rtgs',
    'upi',
    'imps',
    'card',
    'other'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── Token sequence ────────────────────────────────────────────────
-- Drives the per-bill token TOK-YYYY-NNNNN. Year prefix comes from
-- the bill_date, sequence is global (gaps from deletes/dupes are
-- fine — the UNIQUE constraint on bills.token is the source of truth).
CREATE SEQUENCE IF NOT EXISTS public.bill_token_seq;

-- ── Per-profile approver flag ─────────────────────────────────────
-- Mirrors 027's can_approve_cuts. Developer + Owner always qualify
-- in code regardless of the bit; this flag opens the door to a
-- specific non-owner approver in the future (e.g. a senior team_head
-- handling bill review on the owner's behalf).
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS can_approve_bills BOOLEAN NOT NULL DEFAULT FALSE;

-- ── bill_vendors ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.bill_vendors (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name         TEXT NOT NULL UNIQUE,
  category     TEXT NULL,            -- free text: 'cement' / 'steel' / 'tools' / etc
  gstin        TEXT NULL,
  pan          TEXT NULL,
  address      TEXT NULL,
  phone        TEXT NULL,
  email        TEXT NULL,
  bank_name    TEXT NULL,
  bank_account TEXT NULL,            -- masked in UI
  ifsc         TEXT NULL,
  upi_id       TEXT NULL,
  notes        TEXT NULL,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by   UUID NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by   UUID NULL REFERENCES public.profiles(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS bill_vendors_active_name_idx
  ON public.bill_vendors (is_active, name)
  WHERE is_active = TRUE;

-- ── bills ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.bills (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token               TEXT NOT NULL UNIQUE,
  bill_vendor_id      UUID NOT NULL REFERENCES public.bill_vendors(id),
  vendor_bill_no      TEXT NOT NULL,
  bill_date           DATE NOT NULL,
  description         TEXT NOT NULL,
  cost_head           TEXT NULL,                       -- optional free-text: "Tools" / "Cement" / "Site overhead"
  amount_subtotal     NUMERIC(14,2) NOT NULL CHECK (amount_subtotal >= 0),
  gst_percent         NUMERIC(5,2)  NOT NULL DEFAULT 0
                        CHECK (gst_percent >= 0 AND gst_percent <= 100),
  amount_gst          NUMERIC(14,2) NOT NULL GENERATED ALWAYS AS (
                        ROUND(amount_subtotal * gst_percent / 100, 2)
                      ) STORED,
  amount_total        NUMERIC(14,2) NOT NULL GENERATED ALWAYS AS (
                        amount_subtotal + ROUND(amount_subtotal * gst_percent / 100, 2)
                      ) STORED,
  amount_paid         NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),
  amount_outstanding  NUMERIC(14,2) NOT NULL GENERATED ALWAYS AS (
                        amount_subtotal + ROUND(amount_subtotal * gst_percent / 100, 2) - amount_paid
                      ) STORED,
  status              public.bill_status NOT NULL DEFAULT 'pending_approval',
  rejection_note      TEXT NULL,
  inventory_ref_token TEXT NULL,                       -- v2 stub
  submitted_by        UUID NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  submitted_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  approved_by         UUID NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  approved_at         TIMESTAMPTZ NULL,
  rejected_by         UUID NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  rejected_at         TIMESTAMPTZ NULL,
  cancelled_by        UUID NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  cancelled_at        TIMESTAMPTZ NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT bills_vendor_billno_unique UNIQUE (bill_vendor_id, vendor_bill_no)
);

-- Token-assignment trigger. Format TOK-{bill_year}-{seq:5}. Skips if
-- caller already supplied a token (defensive — should never happen
-- via the server actions, but lets a manual SQL insert override).
CREATE OR REPLACE FUNCTION public.assign_bill_token()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  next_n BIGINT;
  yr     TEXT;
BEGIN
  IF NEW.token IS NOT NULL AND NEW.token <> '' THEN
    RETURN NEW;
  END IF;
  yr := to_char(COALESCE(NEW.bill_date, CURRENT_DATE), 'YYYY');
  next_n := nextval('public.bill_token_seq');
  NEW.token := 'TOK-' || yr || '-' || lpad(next_n::text, 5, '0');
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS bills_assign_token ON public.bills;
CREATE TRIGGER bills_assign_token
  BEFORE INSERT ON public.bills
  FOR EACH ROW EXECUTE FUNCTION public.assign_bill_token();

-- ── bill_payments ────────────────────────────────────────────────
-- One row per pay-today proposal. Partial payments produce multiple
-- rows that all reference the same bill_id. proposal_batch_id groups
-- rows the accountant proposed together (used by the pay-today screen
-- so the owner can confirm-or-untick the whole batch in one go).
CREATE TABLE IF NOT EXISTS public.bill_payments (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  bill_id             UUID NOT NULL REFERENCES public.bills(id) ON DELETE RESTRICT,
  status              public.bill_payment_status NOT NULL DEFAULT 'proposed',
  proposed_amount     NUMERIC(14,2) NOT NULL CHECK (proposed_amount > 0),
  proposed_by         UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  proposed_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  proposal_batch_id   UUID NULL,
  confirmed_by        UUID NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  confirmed_at        TIMESTAMPTZ NULL,
  paid_amount         NUMERIC(14,2) NULL CHECK (paid_amount IS NULL OR paid_amount > 0),
  payment_method      public.payment_method NULL,
  payment_reference   TEXT NULL,
  payment_note        TEXT NULL,
  paid_by             UUID NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  paid_at             TIMESTAMPTZ NULL,
  cancelled_by        UUID NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  cancelled_at        TIMESTAMPTZ NULL,
  cancel_reason       TEXT NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT bill_payments_paid_completeness CHECK (
    status <> 'paid'
    OR (paid_amount IS NOT NULL AND payment_method IS NOT NULL AND paid_at IS NOT NULL)
  )
);

-- ── Recalc trigger ───────────────────────────────────────────────
-- Keeps bills.amount_paid in sync with the SUM of all paid
-- bill_payments rows. Also flips bills.status:
--   approved   → fully_paid   when outstanding hits 0
--   fully_paid → approved     when a paid payment is later voided
--                             (cheque bounce, wrong NEFT)
-- This is application-of-record level for the invariant: the
-- triggers run even if a developer fixes a row by hand in the SQL
-- editor. Same defence-in-depth as finish_block_cut RPC.
CREATE OR REPLACE FUNCTION public.recalc_bill_amount_paid()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  target_bill UUID := COALESCE(NEW.bill_id, OLD.bill_id);
BEGIN
  UPDATE public.bills b
     SET amount_paid = COALESCE((
       SELECT SUM(paid_amount)
         FROM public.bill_payments
        WHERE bill_id = target_bill AND status = 'paid'
     ), 0),
     updated_at = NOW()
   WHERE b.id = target_bill;

  UPDATE public.bills
     SET status = 'fully_paid'
   WHERE id = target_bill
     AND status = 'approved'
     AND amount_outstanding = 0;

  UPDATE public.bills
     SET status = 'approved'
   WHERE id = target_bill
     AND status = 'fully_paid'
     AND amount_outstanding > 0;

  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS bill_payments_recalc ON public.bill_payments;
CREATE TRIGGER bill_payments_recalc
  AFTER INSERT OR UPDATE OR DELETE ON public.bill_payments
  FOR EACH ROW EXECUTE FUNCTION public.recalc_bill_amount_paid();

-- ── Indexes ──────────────────────────────────────────────────────
-- Owner audit queue + topbar count
CREATE INDEX IF NOT EXISTS bills_pending_approval_idx
  ON public.bills (submitted_at DESC)
  WHERE status = 'pending_approval';

-- Accountant due-bills dashboard
CREATE INDEX IF NOT EXISTS bills_due_idx
  ON public.bills (bill_date DESC)
  WHERE status = 'approved' AND amount_outstanding > 0;

-- Vendor filter + chronological
CREATE INDEX IF NOT EXISTS bills_vendor_date_idx
  ON public.bills (bill_vendor_id, bill_date DESC);

-- Biller "my submissions"
CREATE INDEX IF NOT EXISTS bills_submitted_by_idx
  ON public.bills (submitted_by, submitted_at DESC);

-- Pay-today screen + topbar count
CREATE INDEX IF NOT EXISTS bill_payments_open_idx
  ON public.bill_payments (proposed_at DESC)
  WHERE status IN ('proposed', 'confirmed');

-- Payment history
CREATE INDEX IF NOT EXISTS bill_payments_paid_idx
  ON public.bill_payments (paid_at DESC)
  WHERE status = 'paid';

-- Batch grouping for pay-today selection
CREATE INDEX IF NOT EXISTS bill_payments_batch_idx
  ON public.bill_payments (proposal_batch_id)
  WHERE proposal_batch_id IS NOT NULL;

-- ── RLS ──────────────────────────────────────────────────────────
-- Server actions all use the admin client (service-role) which
-- bypasses RLS. These read-only policies exist so authenticated
-- session clients can SELECT for any realtime/refresh flow we add
-- later. No write policies — every mutation goes through a server
-- action.
ALTER TABLE public.bill_vendors  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bills         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bill_payments ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "bill_vendors_read_authenticated"  ON public.bill_vendors
    FOR SELECT TO authenticated USING (TRUE);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY "bills_read_authenticated"         ON public.bills
    FOR SELECT TO authenticated USING (TRUE);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY "bill_payments_read_authenticated" ON public.bill_payments
    FOR SELECT TO authenticated USING (TRUE);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

NOTIFY pgrst, 'reload schema';

COMMIT;

-- ──────────────────────────────────────────────────────────────────
-- Post-migration manual step (run separately in the SQL editor):
--
--   UPDATE public.profiles
--      SET can_approve_bills = TRUE
--    WHERE full_name ILIKE 'NARESH%';
--
-- Future approvers get the same UPDATE. Developer + Owner roles
-- always qualify in code regardless of the bit.
-- ──────────────────────────────────────────────────────────────────
