// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(app)/accounts/advances/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/advances/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/advances/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/advances/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/advances/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/advances/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/advances/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/advances">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/advances/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/approvals">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/bank-declines/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/bank-declines">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/bank-declines/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/bills/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/bills/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/bills/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/bills/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/bills/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/bills/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/bills/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/bills/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/bills/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/bills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/bills">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/bills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/bills/scan-multi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/bills/scan-multi">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/bills/scan-multi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/final-audit/flagged/[paymentId]/settle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/final-audit/flagged/[paymentId]/settle">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/final-audit/flagged/[paymentId]/settle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/final-audit/flagged/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/final-audit/flagged">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/final-audit/flagged/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/final-audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/final-audit">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/final-audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/final-audit/verified/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/final-audit/verified">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/final-audit/verified/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/pay-today/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/pay-today">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/pay-today/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/payments/[id]/voucher/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/payments/[id]/voucher">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/payments/[id]/voucher/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/payments">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/reconcile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/reconcile">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/reconcile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/royalty-approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/royalty-approvals">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/royalty-approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/royalty-summary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/royalty-summary">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/royalty-summary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/vendors/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/vendors/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/vendors/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/accounts/vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/vendors">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/accounts/vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/activity-register/[siteId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activity-register/[siteId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/activity-register/[siteId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/activity-register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activity-register">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/activity-register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/ask-ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ask-ai">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/ask-ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/block-journey/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/block-journey">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/block-journey/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/blocks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blocks">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/blocks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/blocks/purchase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blocks/purchase">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/blocks/purchase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/blocks/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blocks/report">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/blocks/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/challans/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/challans/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/challans/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/challans/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/challans/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/challans/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/challans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/challans">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/challans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/expenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/expenses">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/expenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/floor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/floor">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/floor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/rejected/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/rejected">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/rejected/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/storage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/storage">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/storage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/transfer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/transfer">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/transfer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/vendors/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/vendors/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/vendors/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/vendors">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/work-orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/work-orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/work-orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/work-orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/work-orders/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/work-orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/carving/work-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carving/work-orders">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/carving/work-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/challan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/challan">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/challan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/cutting/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cutting/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/cutting/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/cutting/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cutting/approvals">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/cutting/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/cutting/expenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cutting/expenses">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/cutting/expenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/cutting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cutting">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/cutting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/dashboard/emails/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/emails">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/dashboard/emails/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/dashboard/push-urgent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/push-urgent">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/dashboard/push-urgent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/dispatch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dispatch">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/dispatch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/dispatch/rework/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dispatch/rework">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/dispatch/rework/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/inventory/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/approvals">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/inventory/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/inventory/scaffolding/components/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/scaffolding/components">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/inventory/scaffolding/components/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/inventory/scaffolding/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/scaffolding/history">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/inventory/scaffolding/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/inventory/scaffolding/issue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/scaffolding/issue">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/inventory/scaffolding/issue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/inventory/scaffolding/move-yard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/scaffolding/move-yard">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/inventory/scaffolding/move-yard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/inventory/scaffolding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/scaffolding">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/inventory/scaffolding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/inventory/scaffolding/receive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/scaffolding/receive">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/inventory/scaffolding/receive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/inventory/scaffolding/return/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/scaffolding/return">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/inventory/scaffolding/return/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/inventory/scaffolding/sites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/scaffolding/sites">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/inventory/scaffolding/sites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/inventory/scaffolding/writeoff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/scaffolding/writeoff">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/inventory/scaffolding/writeoff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/invoicing/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoicing/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/invoicing/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/invoicing/challans/[id]/convert/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoicing/challans/[id]/convert">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/invoicing/challans/[id]/convert/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/invoicing/challans/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoicing/challans/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/invoicing/challans/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/invoicing/challans/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoicing/challans/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/invoicing/challans/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/invoicing/challans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoicing/challans">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/invoicing/challans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/invoicing/invoices/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoicing/invoices/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/invoicing/invoices/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/invoicing/invoices/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoicing/invoices/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/invoicing/invoices/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/invoicing/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoicing/invoices">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/invoicing/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/invoicing/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoicing/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/invoicing/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/invoicing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoicing">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/invoicing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/invoicing/parties/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoicing/parties/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/invoicing/parties/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/invoicing/parties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoicing/parties">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/invoicing/parties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/invoicing/work-order-doc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoicing/work-order-doc">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/invoicing/work-order-doc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/maintenance/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/maintenance/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/maintenance/tickets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/tickets">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/maintenance/tickets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/reports/various-costing/cnc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/various-costing/cnc">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/reports/various-costing/cnc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/reports/various-costing/cutter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/various-costing/cutter">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/reports/various-costing/cutter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/reports/various-costing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/various-costing">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/reports/various-costing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/site/[temple]/install/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/site/[temple]/install">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/site/[temple]/install/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/site/[temple]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/site/[temple]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/site/[temple]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/site/[temple]/stock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/site/[temple]/stock">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/site/[temple]/stock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/site/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/site">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/site/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/slabs/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/slabs/import">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/slabs/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/slabs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/slabs">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/slabs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/slabs/ready/for-carving/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/slabs/ready/for-carving">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/slabs/ready/for-carving/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/slabs/ready/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/slabs/ready">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/slabs/ready/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/slabs/view/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/slabs/view">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/slabs/view/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/tasks/owner-reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks/owner-reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/tasks/owner-reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/tasks/slab-cancels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks/slab-cancels">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/tasks/slab-cancels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/tasks/slab-imports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks/slab-imports">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/tasks/slab-imports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/temples/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/temples">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/temples/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/vendor/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/vendor/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/vendor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/vendor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(print)/cutting/[id]/labels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cutting/[id]/labels">> = Specific
  const handler = {} as typeof import("../../../src/app/(print)/cutting/[id]/labels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(print)/cutting/[id]/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cutting/[id]/print">> = Specific
  const handler = {} as typeof import("../../../src/app/(print)/cutting/[id]/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(print)/cutting/list-print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cutting/list-print">> = Specific
  const handler = {} as typeof import("../../../src/app/(print)/cutting/list-print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(print)/dispatch/[id]/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dispatch/[id]/print">> = Specific
  const handler = {} as typeof import("../../../src/app/(print)/dispatch/[id]/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/embed/block-journey/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/embed/block-journey">> = Specific
  const handler = {} as typeof import("../../../src/app/embed/block-journey/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/embed/blocks/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/embed/blocks/report">> = Specific
  const handler = {} as typeof import("../../../src/app/embed/blocks/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/embed/slabs/ready/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/embed/slabs/ready">> = Specific
  const handler = {} as typeof import("../../../src/app/embed/slabs/ready/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pending/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pending">> = Specific
  const handler = {} as typeof import("../../../src/app/pending/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/accounts/bill-scan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/accounts/bill-scan">> = Specific
  const handler = {} as typeof import("../../../src/app/api/accounts/bill-scan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/accounts/hdfc-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/accounts/hdfc-export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/accounts/hdfc-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/accounts/hdfc-payment-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/accounts/hdfc-payment-export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/accounts/hdfc-payment-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/accounts/vendor-outstanding-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/accounts/vendor-outstanding-export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/accounts/vendor-outstanding-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/activity-register/proof/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/activity-register/proof/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/activity-register/proof/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ask-ai/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ask-ai">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ask-ai/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/sms-hook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sms-hook">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/sms-hook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/block-journey/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/block-journey/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/block-journey/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/blocks/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blocks/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/blocks/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/carving/challan-pdf/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/carving/challan-pdf/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/carving/challan-pdf/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/carving/gate-pass/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/carving/gate-pass/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/carving/gate-pass/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/carving/work-order-pdf/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/carving/work-order-pdf/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/carving/work-order-pdf/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cutting/done-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cutting/done-pdf">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cutting/done-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/email-snapshot/attachment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email-snapshot/attachment">> = Specific
  const handler = {} as typeof import("../../../src/app/api/email-snapshot/attachment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/email-snapshot/message/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email-snapshot/message">> = Specific
  const handler = {} as typeof import("../../../src/app/api/email-snapshot/message/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/email-snapshot/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email-snapshot/run">> = Specific
  const handler = {} as typeof import("../../../src/app/api/email-snapshot/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/export/full-backup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/full-backup">> = Specific
  const handler = {} as typeof import("../../../src/app/api/export/full-backup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/heartbeat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/heartbeat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/heartbeat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/inventory/component-image/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/component-image/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/inventory/component-image/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/invoicing/work-order-doc/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoicing/work-order-doc/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/invoicing/work-order-doc/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/login-location/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/login-location">> = Specific
  const handler = {} as typeof import("../../../src/app/api/login-location/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/maintenance/proof/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/proof/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/maintenance/proof/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reports/cnc-monthly.xlsx/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/cnc-monthly.xlsx">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reports/cnc-monthly.xlsx/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/slabs/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/slabs/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/slabs/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/slabs/import-template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/slabs/import-template">> = Specific
  const handler = {} as typeof import("../../../src/app/api/slabs/import-template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/temples/master-excel.xlsx/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/temples/master-excel.xlsx">> = Specific
  const handler = {} as typeof import("../../../src/app/api/temples/master-excel.xlsx/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/temples/slab-table.xlsx/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/temples/slab-table.xlsx">> = Specific
  const handler = {} as typeof import("../../../src/app/api/temples/slab-table.xlsx/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/whatsapp-report/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp-report/preview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/whatsapp-report/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/whatsapp-report/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp-report/run">> = Specific
  const handler = {} as typeof import("../../../src/app/api/whatsapp-report/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(print)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(print)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/embed/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/embed">> = Specific
  const handler = {} as typeof import("../../../src/app/embed/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
